create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lead_id bigint references public.leads(id),
  name text not null,
  company text,
  email text,
  phone text,
  country text,
  notes text
);

create unique index if not exists customers_lead_id_key
  on public.customers(lead_id)
  where lead_id is not null;

alter table public.customers enable row level security;

create policy "Allow public read customers"
on public.customers
for select
to anon
using (true);
