create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint not null references public.customers(id),
  product text not null,
  quantity text,
  unit_price numeric not null,
  currency text not null default 'USD',
  incoterm text not null default 'FOB',
  valid_until date,
  notes text,
  status text not null default 'draft'
);

alter table public.quotes enable row level security;

create policy "Allow public read quotes"
on public.quotes
for select
to anon
using (true);
